// pSEO data for programmatic pages

export interface RoleData {
  slug: string;
  title: string;
  description: string;
  tasks: string[];
  painPoints: string[];
  benefits: string[];
}

export interface TaskData {
  slug: string;
  title: string;
  description: string;
  currentWay: string;
  aiWay: string;
  timeSaved: string;
  steps: string[];
}

export interface ComparisonData {
  slug: string;
  name: string;
  description: string;
  pricing: string;
  ezAdvantages: string[];
  theirAdvantages: string[];
  verdict: string;
}

export const ROLES: RoleData[] = [
  { slug: "real-estate-agents", title: "Real Estate Agents", description: "AI employee for real estate agents — manages listings, client follow-ups, market research, and appointment scheduling.", tasks: ["Draft listing descriptions", "Follow up with leads automatically", "Research comparable properties", "Schedule showings and open houses", "Send market update emails to clients"], painPoints: ["Spending hours on listing copy", "Forgetting to follow up with leads", "Manual CMA research", "Juggling multiple client schedules"], benefits: ["50% less time on admin work", "Never miss a lead follow-up", "Instant comparative market analysis", "Automated showing confirmations"] },
  { slug: "lawyers", title: "Lawyers", description: "AI employee for lawyers — drafts correspondence, manages case timelines, researches precedents, and handles client intake.", tasks: ["Draft client correspondence", "Research case precedents", "Manage case deadlines and timelines", "Handle initial client intake", "Prepare meeting briefs"], painPoints: ["Billing for admin time feels wrong", "Research takes hours", "Missing filing deadlines", "Client communication backlog"], benefits: ["More billable hours, less admin", "Instant case research summaries", "Automated deadline tracking", "Faster client response times"] },
  { slug: "coaches", title: "Coaches & Consultants", description: "AI employee for coaches and consultants — manages client communication, creates content, handles scheduling and follow-ups.", tasks: ["Schedule and confirm sessions", "Send session prep materials", "Follow up after sessions", "Create social media content", "Manage client onboarding"], painPoints: ["Admin eats into coaching time", "Inconsistent content posting", "Client scheduling chaos", "Manual onboarding process"], benefits: ["2x more coaching hours", "Daily content on autopilot", "Zero scheduling conflicts", "Streamlined client onboarding"] },
  { slug: "freelancers", title: "Freelancers", description: "AI employee for freelancers — handles invoicing, client communication, project tracking, and prospecting.", tasks: ["Draft and send invoices", "Follow up on late payments", "Track project milestones", "Prospect for new clients", "Manage email inbox"], painPoints: ["Chasing payments is awkward", "No time for prospecting", "Email overwhelm", "Project status tracking"], benefits: ["Automatic payment follow-ups", "Consistent lead pipeline", "Inbox at zero daily", "Clear project dashboards"] },
  { slug: "ecommerce-owners", title: "E-Commerce Owners", description: "AI employee for e-commerce owners — monitors competitors, handles customer emails, manages inventory alerts, and creates product descriptions.", tasks: ["Write product descriptions", "Respond to customer inquiries", "Monitor competitor pricing", "Create promotional emails", "Generate social media posts"], painPoints: ["Product copy takes forever", "Customer emails pile up", "Missing competitor moves", "Inconsistent marketing"], benefits: ["Hundreds of descriptions in minutes", "2-hour email response time", "Real-time competitor tracking", "Daily marketing content"] },
  { slug: "accountants", title: "Accountants", description: "AI employee for accountants — manages client communication, prepares document requests, tracks deadlines, and drafts reports.", tasks: ["Send document request emails", "Track filing deadlines", "Draft client summary reports", "Follow up on missing documents", "Schedule review meetings"], painPoints: ["Tax season email overload", "Chasing missing documents", "Deadline tracking stress", "Report formatting tedium"], benefits: ["Automated document requests", "Never miss a deadline", "Reports in seconds", "Zero email backlog"] },
  { slug: "marketing-agencies", title: "Marketing Agencies", description: "AI employee for marketing agencies — creates content, manages client reporting, handles social media, and tracks campaign performance.", tasks: ["Draft social media posts", "Create weekly client reports", "Research industry trends", "Write blog post drafts", "Monitor campaign metrics"], painPoints: ["Content creation bottleneck", "Manual reporting takes hours", "Keeping up with trends", "Client communication overhead"], benefits: ["10x content output", "One-click client reports", "Real-time trend insights", "Automated client updates"] },
  { slug: "therapists", title: "Therapists & Counselors", description: "AI employee for therapists — manages appointment scheduling, sends session reminders, handles intake forms, and manages waitlists.", tasks: ["Send appointment reminders", "Process intake paperwork", "Manage waitlist communication", "Follow up with no-shows", "Schedule recurring sessions"], painPoints: ["Admin takes away from clients", "No-shows cost money", "Waitlist management chaos", "Intake paperwork burden"], benefits: ["More time with clients", "50% fewer no-shows", "Automated waitlist management", "Paperless intake process"] },
  { slug: "property-managers", title: "Property Managers", description: "AI employee for property managers — handles tenant communication, maintenance requests, rent reminders, and lease renewals.", tasks: ["Send rent reminders", "Coordinate maintenance requests", "Draft lease renewal notices", "Respond to tenant inquiries", "Schedule property inspections"], painPoints: ["Tenant communication overload", "Maintenance coordination chaos", "Missed lease renewals", "After-hours inquiries"], benefits: ["24/7 tenant response", "Streamlined maintenance flow", "Automated lease tracking", "No communication backlog"] },
  { slug: "recruiters", title: "Recruiters", description: "AI employee for recruiters — screens resumes, schedules interviews, sends candidate updates, and manages job postings.", tasks: ["Screen incoming resumes", "Schedule interviews", "Send candidate status updates", "Draft job descriptions", "Follow up with hiring managers"], painPoints: ["Resume screening overload", "Scheduling back-and-forth", "Candidate ghosting", "Job description writing"], benefits: ["AI-powered resume screening", "Automated interview scheduling", "Consistent candidate updates", "Job posts in seconds"] },
  { slug: "financial-advisors", title: "Financial Advisors", description: "AI employee for financial advisors — prepares client meeting briefs, sends market updates, manages follow-ups, and handles compliance documentation.", tasks: ["Prepare client meeting briefs", "Send market update newsletters", "Follow up after reviews", "Track compliance deadlines", "Draft financial summaries"], painPoints: ["Meeting prep takes too long", "Staying compliant is stressful", "Client follow-up gaps", "Market update creation"], benefits: ["Instant meeting prep docs", "Automated compliance tracking", "Zero follow-up gaps", "Daily market briefings"] },
  { slug: "dentists", title: "Dentists & Dental Practices", description: "AI employee for dental practices — manages appointment scheduling, sends treatment reminders, handles patient communication, and reviews follow-up.", tasks: ["Send appointment reminders", "Follow up on treatment plans", "Handle patient inquiries", "Manage recall scheduling", "Draft patient communications"], painPoints: ["No-shows cost thousands", "Treatment follow-up gaps", "Phone call overload", "Patient recall management"], benefits: ["70% fewer no-shows", "Automated treatment follow-ups", "24/7 patient communication", "Systematic recall campaigns"] },
  { slug: "saas-founders", title: "SaaS Founders", description: "AI employee for SaaS founders — handles customer support, creates content, monitors competitors, and manages investor communications.", tasks: ["Draft support responses", "Create product update emails", "Monitor competitor features", "Write blog and social content", "Manage investor updates"], painPoints: ["Support takes away from building", "No time for content", "Missing competitor moves", "Investor updates are a chore"], benefits: ["Instant support drafts", "Weekly content on autopilot", "Real-time competitor alerts", "Polished investor updates"] },
  { slug: "photographers", title: "Photographers", description: "AI employee for photographers — manages booking inquiries, sends contracts, handles follow-ups, and creates social media content.", tasks: ["Respond to booking inquiries", "Send contracts and questionnaires", "Follow up after sessions", "Create social media posts", "Manage gallery delivery"], painPoints: ["Slow response loses bookings", "Contract admin is tedious", "Post-session follow-up gaps", "Social media inconsistency"], benefits: ["Instant booking responses", "Automated contract flow", "Systematic follow-ups", "Daily social content"] },
  { slug: "personal-trainers", title: "Personal Trainers", description: "AI employee for personal trainers — manages client scheduling, sends workout plans, handles nutrition follow-ups, and manages billing.", tasks: ["Schedule and confirm sessions", "Send workout summaries", "Follow up on nutrition goals", "Handle billing and renewals", "Create motivational content"], painPoints: ["Scheduling nightmares", "Manual program delivery", "Client accountability gaps", "Payment chasing"], benefits: ["Zero scheduling conflicts", "Automated program delivery", "Built-in accountability system", "Automatic billing"] },
];

export const TASKS: TaskData[] = [
  { slug: "email-management", title: "Email Management", description: "Automate email management with AI — read, draft, send, and organize emails without lifting a finger.", currentWay: "Manually reading, sorting, drafting, and sending 50-100 emails per day. Context switching between inbox and actual work.", aiWay: "Employee Zero reads your inbox, drafts replies in your voice, follows up automatically, and archives handled threads. You review and approve — that is it.", timeSaved: "10-15 hours/week", steps: ["Connect your Gmail account", "Employee Zero learns your communication style", "It reads incoming emails and drafts appropriate replies", "You review and approve with one click", "Follow-ups happen automatically"] },
  { slug: "calendar-scheduling", title: "Calendar & Scheduling", description: "Automate scheduling with AI — manage your calendar, find free slots, and coordinate meetings without the back-and-forth.", currentWay: "Manual back-and-forth emails to find meeting times. Double-bookings. Forgetting to send confirmations. Missing prep time between meetings.", aiWay: "Employee Zero manages your entire calendar — finds free slots, proposes times, sends confirmations, and blocks prep time automatically.", timeSaved: "5-8 hours/week", steps: ["Connect Google Calendar", "Set your availability preferences", "Employee Zero handles all scheduling requests", "Automatic confirmations and reminders sent", "Prep time blocked before important meetings"] },
  { slug: "social-media-posting", title: "Social Media Posting", description: "Automate social media with AI — create, schedule, and post content across all platforms consistently.", currentWay: "Manually writing posts for each platform. Forgetting to post. Inconsistent scheduling. No time to engage with comments.", aiWay: "Employee Zero creates platform-specific content, schedules posts at optimal times, and drafts responses to comments and DMs.", timeSaved: "8-12 hours/week", steps: ["Connect your social accounts (X, LinkedIn, Instagram, Facebook)", "Tell Employee Zero your content themes and brand voice", "It generates daily posts tailored per platform", "Posts are scheduled at optimal engagement times", "Comment and DM responses drafted automatically"] },
  { slug: "research-reports", title: "Research & Reports", description: "Automate research with AI — get comprehensive reports with cited sources delivered to your inbox on any topic.", currentWay: "Hours of Googling, reading articles, compiling notes, and formatting reports. Often outdated by the time you finish.", aiWay: "Tell Employee Zero what you need. Get a comprehensive, cited research report in minutes. Schedule recurring reports for ongoing monitoring.", timeSaved: "5-10 hours/week", steps: ["Describe what you need researched", "Employee Zero searches, reads, and analyzes dozens of sources", "A structured report is delivered with key findings and citations", "Set up recurring reports for ongoing topics", "Reports improve over time as Employee Zero learns your interests"] },
  { slug: "competitor-monitoring", title: "Competitor Monitoring", description: "Automate competitor tracking with AI — monitor pricing, features, reviews, and market moves in real-time.", currentWay: "Manually checking competitor websites, reading their social media, tracking pricing changes. Easy to miss important moves.", aiWay: "Employee Zero continuously monitors your competitors and sends you alerts when something changes — pricing, features, launches, reviews.", timeSaved: "3-5 hours/week", steps: ["Tell Employee Zero who your competitors are", "It monitors their websites, social media, and review sites", "Weekly summary reports delivered automatically", "Instant alerts for major changes (pricing, launches)", "Competitive positioning recommendations included"] },
  { slug: "invoice-billing", title: "Invoicing & Billing", description: "Automate invoicing with AI — send invoices, track payments, and follow up on overdue accounts automatically.", currentWay: "Creating invoices manually, tracking who has paid, sending awkward follow-up emails for overdue payments.", aiWay: "Employee Zero generates invoices, tracks payment status, and sends professional follow-up sequences for overdue accounts.", timeSaved: "2-4 hours/week", steps: ["Connect your billing details", "Employee Zero drafts and sends professional invoices", "Payment status is tracked automatically", "Overdue accounts get polite but firm follow-up sequences", "Monthly billing summaries generated for your records"] },
  { slug: "customer-support", title: "Customer Support", description: "Automate customer support with AI — draft responses, categorize tickets, and handle common inquiries instantly.", currentWay: "Reading every support email, writing individual responses, categorizing issues, escalating complex problems manually.", aiWay: "Employee Zero reads incoming support requests, drafts responses, categorizes by priority, and handles common questions automatically.", timeSaved: "10-20 hours/week", steps: ["Connect your support email or helpdesk", "Employee Zero learns your product and common issues", "Incoming requests are categorized by type and priority", "Draft responses generated for your review", "Common questions answered automatically with approval"] },
  { slug: "meeting-preparation", title: "Meeting Preparation", description: "Automate meeting prep with AI — get briefing docs, attendee research, and talking points before every meeting.", currentWay: "Scrambling to prepare before meetings. Searching for context in old emails. Going in without a clear agenda.", aiWay: "Employee Zero reads your calendar, researches attendees, pulls relevant context, and delivers a prep brief before every meeting.", timeSaved: "3-5 hours/week", steps: ["Connect your Google Calendar", "Set notification preferences (30 min, 1 hour before meeting)", "Employee Zero researches attendees and pulls relevant context", "A structured brief is delivered with talking points and questions", "Post-meeting notes and action items captured automatically"] },
  { slug: "content-writing", title: "Content Writing", description: "Automate content creation with AI — blog posts, newsletters, and marketing copy in your brand voice.", currentWay: "Staring at a blank page. Spending hours writing one blog post. Inconsistent publishing schedule. Brand voice varies.", aiWay: "Employee Zero generates content drafts in your voice — blog posts, newsletters, product descriptions, email campaigns. You edit and publish.", timeSaved: "8-15 hours/week", steps: ["Share your brand voice guidelines and example content", "Employee Zero learns your style and tone", "Request any content type — blogs, newsletters, copy", "First drafts delivered in minutes, not hours", "Content calendar managed automatically"] },
  { slug: "lead-follow-up", title: "Lead Follow-Up", description: "Automate lead follow-up with AI — never let a prospect go cold with systematic, personalized follow-up sequences.", currentWay: "Manually tracking who needs a follow-up. Forgetting to follow up. Generic follow-up emails that feel robotic.", aiWay: "Employee Zero tracks every lead, sends personalized follow-ups at optimal times, and alerts you when a lead shows buying signals.", timeSaved: "5-8 hours/week", steps: ["Tell Employee Zero about your leads or connect your CRM", "Set follow-up intervals and messaging tone", "Personalized follow-ups sent automatically", "AI detects buying signals and prioritizes hot leads", "Weekly pipeline summary with recommended actions"] },
];

export const COMPARISONS: ComparisonData[] = [
  { slug: "chatgpt", name: "ChatGPT", description: "ChatGPT is a conversational AI that generates text. Employee Zero is an AI employee that does real work — sends emails, manages calendars, posts to social media, and more.", pricing: "$20/mo (Plus)", ezAdvantages: ["Actually sends emails, not just drafts them", "Manages your real calendar", "Posts to your real social media accounts", "Remembers your preferences permanently", "Executes multi-step workflows", "Private — your data never trains other models"], theirAdvantages: ["Better at creative writing", "Wider general knowledge", "Code generation capabilities", "Image generation built-in"], verdict: "ChatGPT is a brilliant chatbot. Employee Zero is an employee. If you need text generated, use ChatGPT. If you need work done, hire Employee Zero." },
  { slug: "virtual-assistant", name: "Virtual Assistant (Human)", description: "Human VAs cost $1,500-$3,000/month and work business hours. Employee Zero costs $29/month and works 24/7.", pricing: "$1,500-$3,000/mo", ezAdvantages: ["98% cheaper ($29 vs $1,500+)", "Available 24/7, not just business hours", "Instant response time (seconds vs minutes/hours)", "Never calls in sick or takes vacation", "Scales instantly — no hiring process", "Perfect consistency every time"], theirAdvantages: ["Better at nuanced judgment calls", "Can handle physical tasks", "Emotional intelligence in client interactions", "Complex problem-solving requiring human creativity"], verdict: "For 90% of admin tasks, Employee Zero delivers better results at 2% of the cost. Keep a human VA for high-judgment work and let Employee Zero handle everything else." },
  { slug: "zapier", name: "Zapier", description: "Zapier connects apps with if-then automations. Employee Zero understands context and makes decisions — it is the difference between a robot and an employee.", pricing: "$29-$99/mo", ezAdvantages: ["Understands context, not just triggers", "Handles tasks that need judgment", "Natural language — no workflow builder needed", "Adapts to new situations without reconfiguration", "Can browse the web and research topics", "Remembers past interactions for better results"], theirAdvantages: ["More app integrations (6,000+)", "Better for simple if-then automations", "More predictable behavior", "No AI hallucination risk"], verdict: "Zapier is great for simple automations. Employee Zero is for tasks that need a brain. Use both: Zapier for triggers, Employee Zero for the thinking." },
  { slug: "notion-ai", name: "Notion AI", description: "Notion AI helps you write inside Notion. Employee Zero works across your entire digital life — email, calendar, social media, files, and more.", pricing: "$10/mo add-on", ezAdvantages: ["Works across all your tools, not just Notion", "Actually sends emails and posts to social media", "Manages your real calendar", "Executes multi-step tasks end-to-end", "Memory that persists across all interactions", "Custom workflows and automation sequences"], theirAdvantages: ["Deep Notion integration", "Better for document organization", "Works within existing Notion workflow", "Cheaper as an add-on"], verdict: "Notion AI is a writing assistant inside Notion. Employee Zero is a full employee across your entire digital life. Different tools for different needs." },
  { slug: "claude", name: "Claude", description: "Claude is an AI assistant focused on helpful, harmless, and honest conversations. Employee Zero goes beyond conversation to execute real tasks in your tools.", pricing: "$20/mo (Pro)", ezAdvantages: ["Sends real emails, not just drafts", "Manages your actual calendar", "Posts to your real social accounts", "Connects to Google Workspace, Stripe, HubSpot", "Persistent memory across interactions", "Executes multi-step automations"], theirAdvantages: ["Better at long-form analysis", "Stronger reasoning capabilities", "Better at nuanced writing", "Larger context window"], verdict: "Claude is one of the best AI chatbots. Employee Zero is an AI employee. Claude helps you think. Employee Zero does the work." },
  { slug: "microsoft-copilot", name: "Microsoft Copilot", description: "Copilot works within Microsoft 365. Employee Zero works with Google Workspace, social media, and dozens more tools.", pricing: "$30/mo (Pro)", ezAdvantages: ["Works with Google Workspace (not just Microsoft)", "Manages social media accounts", "Cheaper ($29 vs $30) with more capabilities", "Custom workflows and automation", "Not locked into Microsoft ecosystem", "Memory and context that improves over time"], theirAdvantages: ["Deep Excel and Word integration", "Enterprise security and compliance", "Works within familiar Microsoft apps", "Better for large enterprise teams"], verdict: "If you are all-in on Microsoft 365, Copilot makes sense. For everyone else — especially Google Workspace users and solopreneurs — Employee Zero delivers more value for less money." },
];
